### ISSUE TITLE
Publish

### ISSUE THREAD

**Issue by ManuelLeitner** [rstropek-teaching/contact-list-quiz-5ahif-ManuelLeitner#1]
The service is now available on the [internet](http://contactsservice.azurewebsites.net/)

**Comment by rstropek** [comment]
@ManuelLeitner Thank you for your homework. Works great 👍  Your extra point is secured.

I found some minor issues (differences of your implementation compared to the Swagger spec). Still, your extra point is secured.

* `id` is generated by the server in your solution. The Swagger spec defined that the id can be sent by the client. I like your solution. This is not a bug, more a valid enhancement.

* The *findByName* operation should receive the *nameFilter* via parameter, not via URL path segment.

In general, good solution (as always). Congrats.

Greetings,
Rainer Stropek.
